version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

commands:
  publish:
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install Git LFS
          command: |
            wget -O lfs.deb https://packagecloud.io/github/git-lfs/packages/debian/stretch/git-lfs_2.7.2_amd64.deb/download
            sudo dpkg -i lfs.deb

            git lfs install
            git lfs pull
      - run: ./publish.sh

jobs:
  ap_south_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: ap-south-1
    steps:
      - publish

  ap_southeast_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: ap-southeast-1
    steps:
      - publish

  ap_southeast_2:
    executor: aws-cli/default
    environment:
      TARGET_REGION: ap-southeast-2
    steps:
      - publish

  eu_central_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: eu-central-1
    steps:
      - publish

  eu_west_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: eu-west-1
    steps:
      - publish

  eu_west_2:
    executor: aws-cli/default
    environment:
      TARGET_REGION: eu-west-2
    steps:
      - publish

  sa_east_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: sa-east-1
    steps:
      - publish

  us_east_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: us-east-1
    steps:
      - publish

  us_east_2:
    executor: aws-cli/default
    environment:
      TARGET_REGION: us-east-2
    steps:
      - publish

  us_west_2:
    executor: aws-cli/default
    environment:
      TARGET_REGION: us-west-2
    steps:
      - publish

workflows:
  version: 2
  publish:
    jobs:
      - ap_south_1:
          context: libreoffice-lambda-layer
          filters:
            branches:
              only:
                - master

      - ap_southeast_1:
          context: libreoffice-lambda-layer
          filters:
            branches:
              only:
                - master

      - ap_southeast_2:
          context: libreoffice-lambda-layer
          filters:
            branches:
              only:
                - master

      - eu_central_1:
          context: libreoffice-lambda-layer
          filters:
            branches:
              only:
                - master

      - eu_west_1:
          context: libreoffice-lambda-layer
          filters:
            branches:
              only:
                - master

      - eu_west_2:
          context: libreoffice-lambda-layer
          filters:
            branches:
              only:
                - master

      - sa_east_1:
          context: libreoffice-lambda-layer
          filters:
            branches:
              only:
                - master

      - us_east_1:
          context: libreoffice-lambda-layer
          filters:
            branches:
              only:
                - master

      - us_east_2:
          context: libreoffice-lambda-layer
          filters:
            branches:
              only:
                - master

      - us_west_2:
          context: libreoffice-lambda-layer
          filters:
            branches:
              only:
                - master
